### ISSUE TITLE
[Dockerfile] curl  for Melodic/Kinetic does not look beyond page 1 in releases

### ISSUE THREAD

**Issue by simwijs** [awesomebytes/pepper_os#3]
Can fix by getting url for the "next" button on /releases
I did this in bash, replace export by RUN for dockerfile
`export release_url="https://github.com/awesomebytes/ros_overlay_on_gentoo_prefix_32b/releases"`

# STEP 1
`export last_desktop_url=``curl -s -L $release_url | grep -m 1 "ROS Melodic desktop" | cut -d '"' -f2 | xargs -n 1 printf "http://github.com%s\n"`

# STEP 2
### check if the length of the last_desktop_url  is empty for melodic, if so, get the next page
###... if stmnt ...
`export next_page_url = ``curl -s -L $release_url | grep -m 1 "Next" | cut -d '"' -f8`
`export release_url=$next_page_url`

# REDO STEP 1-2 if necessary
#... try get the last_desktop_url again, maybe limit for 10 pages or something in a while loop

**Comment by awesomebytes** [comment]
This change has been added, now we loop over pages until we find a release. Your logic had a little mistake (or it was just an example and I misunderstood) where it was trying to download all releases of the page haha

Now it's patched up and working: https://github.com/awesomebytes/pepper_os/blob/master/Dockerfile#L7-L22

Closing the issue :)
