### ISSUE TITLE
Instructions in readme for distribution install

### ISSUE THREAD

**Issue by AndrewJSchoen** [awesomebytes/pepper_os#5]
I noticed that the instructions in the readme specify

```
cat pepper_os_ros-kinetic-x86_*.tar.gz.part-* > pepper_os_ros-kinetic-x86.tar.gz
```

However, the most recent releases seem to use lzma for the compression. After changing the relevant names and commands, things worked correctly, but just wanted to let you know!

**Comment by awesomebytes** [comment]
Hey @AndrewJSchoen I just updated the README. I also unified it for both branches and added a couple of extra comments. Thanks for the feedback! I hope it is working well for you.

Let me know if you are finding issues, and I'm curious also to know what's your workflow with it.

**Comment by AndrewJSchoen** [comment]
Will do. So far, no issues, other than that. We are a lab that works with ROS, across a number of different robotic platforms, and will be interested in exploring the navigation capabilities of the robot.

I know that Aldebaran provides some ROS packages for some work, but I actually found them a bit onerous, and actually not as performant for some things. So we actually have started development on some more focused implementations, which we may be making public once it is a bit more concrete and formalized. Let me know if that would be interesting for you.
